- hosts: localhost
  vars_files:
    - host_vars/mastodon.yaml
  gather_facts: false

  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: ~/.ssh/id_jia.pem
    - ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  roles:
    - role: common
    - role: harvester


