---
- name: Add a node to the existing couchDB cluster.
  hosts: couchdb_coordinator
  become: true
  vars:
    couchdb_version: "3.2.1"
    docker_users:
      - "ubuntu"

  # TODO: make dynamic and add ansible vault variables for cluster values
  # TODO: In making dynamic, ensure that new node is deployed
  tasks:
    - uri:
        method: POST
        url: "http://127.0.0.1:5984/_cluster_setup"
        user: admin
        password: admin
        force_basic_auth: yes
        return_content: yes
        status_code: 201
        headers:
          Content-Type: application/json
        # TODO:
        # Add credentials from ansible value here
        body: |
          {
            "action": "enable_cluster",
            "bind_address":"0.0.0.0",
            "username": "admin",
            "password":"admin",
            "port": 5984,
            "node_count": "2",
            "remote_node": "172.26.131.114",
            "remote_current_user": "admin",
            "remote_current_password": "admin"
          }
      register: json_response1

    - debug: msg={{json_response1}}

    # TODO: low priority, add error handling
    - uri:
        method: POST
        url: "http://127.0.0.1:5984/_cluster_setup"
        user: admin
        password: admin
        force_basic_auth: yes
        return_content: yes
        status_code: 201
        headers:
          Content-Type: application/json
        # TODO:
        # Add credentials from ansible value here
        body: |
          {
            "action": "add_node",
            "host": "172.26.131.114",
            "port": 5984,
            "username": "admin",
            "password": "admin"
          }
      register: json_response2

    - debug: msg={{json_response2}}

    - uri:
        method: POST
        url: "http://127.0.0.1:5984/_cluster_setup"
        user: admin
        password: admin
        force_basic_auth: yes
        return_content: yes
        status_code: 201
        headers:
          Content-Type: application/json
        # TODO:
        # Add credentials from ansible value here
        body: |
          {
            "action": "finish_cluster,
          }
      register: json_response3

    - debug: msg={{json_response3}}
