---
- name: Install Docker.
  hosts: 172.26.135.240
  become: true
  vars:
    couchdb_version: "3.2.1"
    docker_users:
      - "ubuntu"

  tasks:
    # - name: Test
    #   debug: "{{ lookup('file','add_node.json') }}"

    # - name: Initiate cluster
    #   command: >
    #     curl -XPOST "http://admin:admin@127.0.0.1:5984/_cluster_setup" >
    #     --header "Content-Type: application/json" >
    #     --data "{{ lookup('file','add_node.json') }}"

    # - name: Contact the masternode and initiate cluster creation
    #   uri:
    #     url: http://127.0.0.1:5984
    #     url_username: "admin"
    #     url_password: "admin"
    #     body: "{{ lookup('file','initiate_cluster.json') }}"
    #     method: POST
    #     body_format: json
    #     headers:
    #       Content-Type: "application/json"
    #       X-Application-Username: "admin"
    #       X-Application-Password: "admin"

    # - name: Inform the masternode of the additional node
    #   uri:
    #     url: http://127.0.0.1:5984
    #     body: "{{ lookup('file','add_node.json') }}"
    #     method: POST
    #     body_format: json
    #     headers:
    #       Content-Type: "application/json"

    # - name: Finish the cluster setup with the masternode
    #   uri:
    #     url: http://127.0.0.1:5984
    #     url_username: "admin"
    #     url_password: "admin"
    #     body: "{{ lookup('file','finish_cluster.json') }}"
    #     method: POST
    #     body_format: json
    #     headers:
    #       Content-Type: "application/json"
